development:
  adapter: postgresql
  database: ninefold_performance_development
  pool: 5
  timeout: 5000
  host: /tmp

test:
  adapter: postgresql
  database: ninefold_performance_test
  pool: 5
  timeout: 5000
  host: /tmp
